# 1. Read data

In [ ]:
import pandas as pd
import numpy as np
from collections import defaultdict

In [ ]:
from google.colab import files
data = files.upload()

Saving true_1000_fulldata.csv to true_1000_fulldata.csv


In [ ]:
raw_data = pd.read_csv('true_1000_fulldata.csv')
sa3_num = len(raw_data['SA3 Code'].unique())

In [ ]:
raw_data.head()

Year  SA3 Code         SA3 Name  m0-4  m5-9  m10-14  m15-19  m20-24  \
0  1991     10101  Goulburn - Yass  2603  2565    2517    2472    2178   
1  1991     10102       Queanbeyan  1593  1362    1223    1406    1743   
2  1991     10103  Snowy Mountains   741   641     577     591     848   
3  1991     10104      South Coast  1985  1987    1697    1358     963   
4  1991     10201          Gosford  5373  5182    4631    4802    3928   

   m25-29  m30-34  ...  f45-49  f50-54  f55-59  f60-64  f65-69  f70-74  \
0    2392    2478  ...    1859    1591    1412    1382    1252     967   
1    1803    1670  ...     991     745     611     575     544     393   
2    1037    1047  ...     504     413     328     320     258     237   
3    1258    1838  ...    1318    1370    1651    2166    2075    1437   
4    4659    5303  ...    3709    2884    2884    3567    4002    3573   

   f75-79  f80-84  f85+   Total  
0     799     493   353   61667  
1     275     177   105   35281  
2     152      97    59   18092  
3     958     455   314   53440  
4    2661    1565   965  135708  

[5 rows x 40 columns]

In [ ]:
raw_data.columns

Index(['Year', 'SA3 Code', 'SA3 Name', 'm0-4', 'm5-9', 'm10-14', 'm15-19',
       'm20-24', 'm25-29', 'm30-34', 'm35-39', 'm40-44', 'm45-49', 'm50-54',
       'm55-59', 'm60-64', 'm65-69', 'm70-74', 'm75-79', 'm80-84', 'm85+',
       'f0-4', 'f5-9', 'f10-14', 'f15-19', 'f20-24', 'f25-29', 'f30-34',
       'f35-39', 'f40-44', 'f45-49', 'f50-54', 'f55-59', 'f60-64', 'f65-69',
       'f70-74', 'f75-79', 'f80-84', 'f85+', 'Total'],
      dtype='object')

In [ ]:
raw_data['m_total'] = raw_data.apply(lambda x: x['m0-4']+x['m5-9']+x['m10-14']+x['m15-19']+
                                               x['m20-24']+x['m25-29']+x['m30-34']+x['m35-39']+
                                               x['m40-44']+x['m45-49']+x['m50-54']+x['m55-59']+
                                               x['m60-64']+x['m65-69']+x['m70-74']+x['m75-79']+
                                               x['m80-84']+x['m85+'], axis=1)

In [ ]:
raw_data['f_total'] = raw_data.apply(lambda x: x['f0-4']+x['f5-9']+x['f10-14']+x['f15-19']+
                                               x['f20-24']+x['f25-29']+x['f30-34']+x['f35-39']+
                                               x['f40-44']+x['f45-49']+x['f50-54']+x['f55-59']+
                                               x['f60-64']+x['f65-69']+x['f70-74']+x['f75-79']+
                                               x['f80-84']+x['f85+'], axis=1)

In [ ]:
assert((raw_data['m_total']+raw_data['f_total'] == raw_data['Total']).all())

In [ ]:
raw_data

Year  SA3 Code         SA3 Name  m0-4  m5-9  m10-14  m15-19  m20-24  \
0     1991     10101  Goulburn - Yass  2603  2565    2517    2472    2178   
1     1991     10102       Queanbeyan  1593  1362    1223    1406    1743   
2     1991     10103  Snowy Mountains   741   641     577     591     848   
3     1991     10104      South Coast  1985  1987    1697    1358     963   
4     1991     10201          Gosford  5373  5182    4631    4802    3928   
...    ...       ...              ...   ...   ...     ...     ...     ...   
6820  2011     80105   North Canberra  1151  1004     901    1753    4064   
6821  2011     80106   South Canberra   601   607     659     739     897   
6822  2011     80107      Tuggeranong  3122  2922    3165    3730    3672   
6823  2011     80108     Weston Creek   873   803     672     679     656   
6824  2011     80109            Woden   923   974    1032    1065    1187   

      m25-29  m30-34  ...  f55-59  f60-64  f65-69  f70-74  f75-79  f80-84  \
0       2392    2478  ...    1412    1382    1252     967     799     493   
1       1803    1670  ...     611     575     544     393     275     177   
2       1037    1047  ...     328     320     258     237     152      97   
3       1258    1838  ...    1651    2166    2075    1437     958     455   
4       4659    5303  ...    2884    3567    4002    3573    2661    1565   
...      ...     ...  ...     ...     ...     ...     ...     ...     ...   
6820    3371    2345  ...    1150     950     752     618     584     490   
6821    1281     894  ...     859     746     483     393     326     396   
6822    3338    2918  ...    3088    2291    1293     889     652     456   
6823     692     724  ...     701     935     701     494     344     242   
6824    1262    1094  ...     994     890     960     796     615     499   

      f85+   Total  m_total  f_total  
0      353   61667    31422    30245  
1      105   35281    17948    17333  
2       59   18092     9665     8427  
3      314   53440    27048    26392  
4      965  135708    66257    69451  
...    ...     ...      ...      ...  
6820   538   49910    25390    24520  
6821   498   25176    12382    12794  
6822   364   89319    44209    45110  
6823   341   23354    11478    11876  
6824   567   34124    16702    17422  

[6825 rows x 42 columns]

In [ ]:
sa3_codes = raw_data['SA3 Code'].unique()

# 2. Split Train, Validation, Test set

In [ ]:
train_data = raw_data[(raw_data['Year']>=1991) & (raw_data['Year']<=2001)]
#val_data = raw_data[(raw_data['Year']>=2002) & (raw_data['Year']<=2005)]
# remove vali 10-10
test_data = raw_data[(raw_data['Year']>=2002) & (raw_data['Year']<=2011)]

In [ ]:
# Split the data by sex
age_groups = ['0-4','5-9', '10-14', '15-19', '20-24', '25-29', '30-34', '35-39','40-44', '45-49', '50-54', '55-59', '60-64', '65-69', '70-74','75-79', '80-84', '85+']
population_m_dict = defaultdict(dict)
population_f_dict = defaultdict(dict)

In [ ]:
# save population for each year into lists
for sa3_code in sa3_codes:
  population_m_dict[sa3_code] = dict()
  population_f_dict[sa3_code] = dict()
  for year in range(1991,2012):
    if(raw_data[(raw_data['Year']==year) & (raw_data['SA3 Code']==sa3_code)]['Total'].size>0):
      population_m_dict[sa3_code][year] = raw_data[(raw_data['Year']==year) & (raw_data['SA3 Code']==sa3_code)][['m0-4',
                              'm5-9', 'm10-14', 'm15-19', 'm20-24', 'm25-29', 'm30-34', 'm35-39',
                              'm40-44', 'm45-49', 'm50-54', 'm55-59', 'm60-64', 'm65-69', 'm70-74',
                              'm75-79', 'm80-84', 'm85+']].values.tolist()[0]
      population_f_dict[sa3_code][year] = raw_data[(raw_data['Year']==year) & (raw_data['SA3 Code']==sa3_code)][['f0-4', 'f5-9', 'f10-14', 'f15-19',
                              'f20-24', 'f25-29', 'f30-34', 'f35-39', 'f40-44', 'f45-49', 'f50-54',
                              'f55-59', 'f60-64', 'f65-69', 'f70-74', 'f75-79', 'f80-84', 'f85+']].values.tolist()[0]

In [ ]:
pd.DataFrame(population_m_dict)

10101  \
1991  [2603, 2565, 2517, 2472, 2178, 2392, 2478, 231...   
1992  [2605, 2567, 2499, 2371, 2183, 2294, 2483, 233...   
1993  [2585, 2557, 2480, 2294, 2145, 2183, 2455, 234...   
1994  [2557, 2551, 2466, 2244, 2098, 2087, 2425, 234...   
1995  [2508, 2561, 2446, 2204, 2018, 2047, 2359, 237...   
1996  [2466, 2582, 2426, 2212, 1914, 2038, 2286, 241...   
1997  [2407, 2557, 2405, 2206, 1809, 2018, 2213, 245...   
1998  [2323, 2584, 2389, 2193, 1775, 1986, 2121, 247...   
1999  [2284, 2592, 2421, 2147, 1787, 1900, 2106, 243...   
2000  [2237, 2580, 2448, 2129, 1785, 1841, 2071, 242...   
2001  [2248, 2450, 2467, 2141, 1740, 1768, 2045, 239...   
2002  [2234, 2419, 2479, 2186, 1749, 1720, 2054, 234...   
2003  [2236, 2399, 2477, 2189, 1793, 1716, 2055, 227...   
2004  [2177, 2398, 2486, 2207, 1766, 1712, 2021, 220...   
2005  [2154, 2366, 2520, 2239, 1771, 1693, 2007, 217...   
2006  [2083, 2368, 2524, 2246, 1777, 1702, 1959, 216...   
2007  [2153, 2321, 2516, 2283, 1780, 1720, 1888, 216...   
2008  [2214, 2326, 2473, 2288, 1801, 1739, 1883, 222...   
2009  [2286, 2305, 2490, 2320, 1863, 1732, 1867, 226...   
2010  [2358, 2297, 2507, 2352, 1870, 1713, 1846, 223...   
2011  [2350, 2338, 2532, 2420, 1806, 1697, 1768, 220...   

                                                  10102  \
1991  [1593, 1362, 1223, 1406, 1743, 1803, 1670, 139...   
1992  [1625, 1411, 1264, 1375, 1774, 1774, 1741, 147...   
1993  [1638, 1445, 1305, 1348, 1769, 1730, 1785, 155...   
1994  [1643, 1482, 1340, 1334, 1746, 1707, 1834, 161...   
1995  [1631, 1524, 1375, 1328, 1701, 1704, 1841, 168...   
1996  [1610, 1563, 1397, 1336, 1613, 1729, 1828, 175...   
1997  [1700, 1556, 1423, 1342, 1536, 1743, 1791, 183...   
1998  [1750, 1530, 1488, 1327, 1466, 1700, 1803, 185...   
1999  [1777, 1588, 1553, 1368, 1428, 1692, 1810, 191...   
2000  [1820, 1664, 1620, 1454, 1451, 1685, 1861, 204...   
2001  [1709, 1746, 1767, 1565, 1364, 1449, 1759, 206...   
2002  [1742, 1822, 1774, 1598, 1414, 1485, 1823, 203...   
2003  [1778, 1843, 1816, 1675, 1481, 1506, 1887, 205...   
2004  [1761, 1848, 1842, 1740, 1507, 1493, 1879, 201...   
2005  [1790, 1860, 1860, 1804, 1541, 1542, 1857, 205...   
2006  [1826, 1846, 1929, 1833, 1585, 1583, 1801, 215...   
2007  [1841, 1877, 1946, 1860, 1674, 1624, 1807, 219...   
2008  [1869, 1932, 1902, 1877, 1775, 1735, 1802, 222...   
2009  [1897, 1904, 1935, 1874, 1909, 1798, 1799, 220...   
2010  [1917, 1920, 1944, 1877, 1925, 1901, 1792, 218...   
2011  [1937, 1852, 1976, 1898, 1873, 1977, 1789, 210...   

                                                  10103  \
1991  [741, 641, 577, 591, 848, 1037, 1047, 890, 743...   
1992  [740, 645, 597, 566, 844, 988, 1032, 914, 762,...   
1993  [736, 643, 610, 553, 833, 938, 999, 936, 777, ...   
1994  [728, 650, 626, 539, 812, 900, 980, 953, 804, ...   
1995  [714, 652, 639, 532, 777, 884, 937, 981, 829, ...   
1996  [701, 665, 655, 533, 730, 871, 888, 1005, 861,...   
1997  [706, 664, 633, 566, 678, 837, 814, 999, 865, ...   
1998  [704, 662, 610, 619, 621, 815, 779, 993, 892, ...   
1999  [681, 672, 618, 650, 598, 793, 765, 955, 870, ...   
2000  [643, 657, 634, 677, 609, 784, 733, 881, 887, ...   
2001  [600, 699, 704, 681, 551, 607, 652, 728, 822, ...   
2002  [579, 703, 721, 692, 562, 589, 683, 683, 826, ...   
2003  [571, 709, 720, 672, 562, 594, 656, 677, 833, ...   
2004  [551, 705, 712, 672, 587, 585, 650, 671, 808, ...   
2005  [562, 682, 729, 650, 590, 559, 673, 651, 789, ...   
2006  [584, 656, 735, 646, 582, 546, 645, 691, 758, ...   
2007  [613, 625, 740, 678, 568, 534, 630, 706, 706, ...   
2008  [627, 599, 754, 680, 584, 553, 598, 669, 700, ...   
2009  [649, 584, 762, 679, 593, 559, 558, 672, 714, ...   
2010  [668, 591, 730, 695, 592, 558, 532, 691, 686, ...   
2011  [663, 636, 698, 715, 589, 535, 505, 660, 705, ...   

                                                  10104  \
1991  [1985, 1987, 1697, 1358, 963, 1258, 1838, 2141...   
1992  [1962, 2038, 1792, 1355, 991,

In [ ]:
def split_sequence(sequence, n_steps):
	X, y = list(), list()
	for i in range(len(sequence)):
		# find the end of this pattern
		end_ix = i + n_steps
		# check if we are beyond the sequence
		if end_ix > len(sequence)-1:
			break
		# gather input and output parts of the pattern
		seq_x, seq_y = sequence[i:end_ix], sequence[end_ix]
		X.append(seq_x)
		y.append(seq_y)
	return np.array(X), np.array(y)

In [ ]:
# define input sequence
male_sample_data = list(population_m_dict[10101.0].values())
# choose a number of time steps
n_steps = 5
# split into samples
X, y = split_sequence(male_sample_data, n_steps)
# summarize the data
for i in range(len(X)):
	print(X[i], y[i])

[[2603 2565 2517 2472 2178 2392 2478 2312 2296 1999 1735 1502 1513 1170
   765  506  260  159]
 [2605 2567 2499 2371 2183 2294 2483 2331 2267 2099 1754 1524 1489 1214
   807  519  269  163]
 [2585 2557 2480 2294 2145 2183 2455 2345 2247 2198 1767 1559 1470 1251
   853  532  280  166]
 [2557 2551 2466 2244 2098 2087 2425 2348 2244 2241 1827 1584 1447 1284
   898  538  300  169]
 [2508 2561 2446 2204 2018 2047 2359 2379 2244 2277 1879 1622 1429 1310
   927  561  302  172]] [2466 2582 2426 2212 1914 2038 2286 2411 2257 2312 1939 1661 1421 1343
  952  599  309  177]
[[2605 2567 2499 2371 2183 2294 2483 2331 2267 2099 1754 1524 1489 1214
   807  519  269  163]
 [2585 2557 2480 2294 2145 2183 2455 2345 2247 2198 1767 1559 1470 1251
   853  532  280  166]
 [2557 2551 2466 2244 2098 2087 2425 2348 2244 2241 1827 1584 1447 1284
   898  538  300  169]
 [2508 2561 2446 2204 2018 2047 2359 2379 2244 2277 1879 1622 1429 1310
   927  561  302  172]
 [2466 2582 2426 2212 1914 2038 2286 2411 2257 2312

## 3.Train and Predict

In [ ]:
# train data
train_x = X[:6]
train_y = y[:6]
# validation data
#val_x = X[6:10]
#val_y = y[6:10]
# test data
test_x = X[6]
test_y = y[6]

In [ ]:
# univariate lstm example
from numpy import array
from keras.models import Sequential
from keras.layers import LSTM
from keras.layers import Dense

In [ ]:

# reshape from [samples, timesteps] into [samples, timesteps, features]
n_features = 18
train_x = train_x.reshape((train_x.shape[0], train_x.shape[1], n_features))
# define model
model = Sequential()
model.add(LSTM(100, activation='relu', input_shape=(n_steps, n_features)))
model.add(Dense(18))
model.compile(optimizer='adam', loss='mse')
# fit model
history = model.fit(train_x, train_y, epochs=200, verbose=0)

# demonstrate prediction
x_input = test_x
x_input = x_input.reshape((1, n_steps, n_features))

prediction_list = []
for iter in range(10):
  prediction = model.predict(x_input, verbose=0)
  prediction_list.append(prediction)

  prediction = prediction.reshape(1,1,18)
  x_input = np.hstack((x_input,prediction)) #add the latest prediction
  x_input = x_input[0][1:].reshape(1,n_steps,n_features)  #delete the first value



In [ ]:
# 10 years prediction on male data
prediction_list

[array([[2272.2795 , 2234.0793 , 2375.492  , 2135.726  , 2007.0968 ,
         1710.2957 , 1792.1785 , 2177.583  , 2138.5156 , 2075.5557 ,
         1865.9525 , 1749.9272 , 1252.2714 , 1403.5824 ,  906.71716,
          616.9245 ,  592.0673 ,  367.1714 ]], dtype=float32),
 array([[2231.4146 , 2219.2227 , 2362.673  , 2136.4385 , 1991.001  ,
         1686.6012 , 1784.619  , 2182.26   , 2134.4934 , 2081.7317 ,
         1842.7004 , 1739.5612 , 1240.917  , 1380.1228 ,  921.55005,
          613.7746 ,  595.8151 ,  374.22577]], dtype=float32),
 array([[2354.1711 , 2177.558  , 2260.203  , 1990.751  , 2012.0596 ,
         1595.3604 , 1883.2499 , 2018.7745 , 1951.3003 , 2029.3512 ,
         1897.0109 , 1664.0958 , 1267.9292 , 1167.8663 , 1026.2167 ,
          659.36554,  402.69867,  454.67682]], dtype=float32),
 array([[2535.6924  , 2641.952   , 2441.7937  , 2032.2294  , 1620.3866  ,
         1880.5629  , 2439.6282  , 2356.0227  , 2179.4954  , 2188.733   ,
         2479.8254  , 1785.1552  , 1896.24

In [ ]:
# prediction for SA3 code(10101) in 2006
prediction_list[4]

array([[2430.6108 , 2594.7026 , 2449.5156 , 2051.239  , 1590.0394 ,
        1961.9562 , 2375.4187 , 2409.0933 , 2281.2615 , 2138.0994 ,
        2418.9304 , 1808.8696 , 1744.927  , 1298.5858 , 1116.6942 ,
         581.9371 ,  191.99825,   96.07537]], dtype=float32)

In [ ]:
# true data
population_m_dict[10101][2006]

[2083,
 2368,
 2524,
 2246,
 1777,
 1702,
 1959,
 2167,
 2452,
 2461,
 2278,
 2407,
 1946,
 1551,
 1188,
 976,
 545,
 317]

In [ ]:
# prediction for SA3 code(10101) in 2011
prediction_list[-1]

array([[2523.6738 , 2160.17   , 2490.6218 , 1973.9579 , 2133.888  ,
        1461.7668 , 2068.44   , 2503.6602 , 2074.698  , 2175.406  ,
        1966.6218 , 1604.0509 ,  816.8614 , 1199.5541 ,  916.45483,
         889.0738 ,  531.8225 ,  588.2581 ]], dtype=float32)

In [ ]:
# true data
population_m_dict[10101][2011]

[2350,
 2338,
 2532,
 2420,
 1806,
 1697,
 1768,
 2204,
 2423,
 2577,
 2555,
 2331,
 2422,
 1950,
 1483,
 1004,
 743,
 490]