# 1. Read data

In [ ]:
import pandas as pd
import numpy as np
from collections import defaultdict

In [ ]:
from google.colab import files
data = files.upload()

Saving above1000.csv to above1000 (1).csv


In [ ]:
raw_data = pd.read_csv('above1000.csv')
sa3_num = len(raw_data['SA3 Code'].unique())

In [ ]:
raw_data.head()

Unnamed: 0  index  Year  S/T Code         S/T Name  GCCSA Code  \
0           0      1  1991       1.0  New South Wales        12.0   
1           1      2  1991       1.0  New South Wales        12.0   
2           2      3  1991       1.0  New South Wales        12.0   
3           3      4  1991       1.0  New South Wales        12.0   
4           4      5  1991       1.0  New South Wales        11.0   

       GCCSA Name  SA4 Code        SA4 Name  SA3 Code  ... f45-49  f50-54  \
0     Rest of NSW     101.0  Capital Region   10101.0  ...   1859    1591   
1     Rest of NSW     101.0  Capital Region   10102.0  ...    991     745   
2     Rest of NSW     101.0  Capital Region   10103.0  ...    504     413   
3     Rest of NSW     101.0  Capital Region   10104.0  ...   1318    1370   
4  Greater Sydney     102.0   Central Coast   10201.0  ...   3709    2884   

   f55-59  f60-64  f65-69  f70-74  f75-79  f80-84  f85+   Total  
0    1412    1382    1252     967     799     493   353   61667  
1     611     575     544     393     275     177   105   35281  
2     328     320     258     237     152      97    59   18092  
3    1651    2166    2075    1437     958     455   314   53440  
4    2884    3567    4002    3573    2661    1565   965  135708  

[5 rows x 48 columns]

In [ ]:
raw_data.columns

Index(['Unnamed: 0', 'index', 'Year', 'S/T Code', 'S/T Name', 'GCCSA Code',
       'GCCSA Name', 'SA4 Code', 'SA4 Name', 'SA3 Code', 'SA3 Name', 'm0-4',
       'm5-9', 'm10-14', 'm15-19', 'm20-24', 'm25-29', 'm30-34', 'm35-39',
       'm40-44', 'm45-49', 'm50-54', 'm55-59', 'm60-64', 'm65-69', 'm70-74',
       'm75-79', 'm80-84', 'm85+', 'f0-4', 'f5-9', 'f10-14', 'f15-19',
       'f20-24', 'f25-29', 'f30-34', 'f35-39', 'f40-44', 'f45-49', 'f50-54',
       'f55-59', 'f60-64', 'f65-69', 'f70-74', 'f75-79', 'f80-84', 'f85+',
       'Total'],
      dtype='object')

In [ ]:
raw_data['m_total'] = raw_data.apply(lambda x: x['m0-4']+x['m5-9']+x['m10-14']+x['m15-19']+
                                               x['m20-24']+x['m25-29']+x['m30-34']+x['m35-39']+
                                               x['m40-44']+x['m45-49']+x['m50-54']+x['m55-59']+
                                               x['m60-64']+x['m65-69']+x['m70-74']+x['m75-79']+
                                               x['m80-84']+x['m85+'], axis=1)

In [ ]:
raw_data['f_total'] = raw_data.apply(lambda x: x['f0-4']+x['f5-9']+x['f10-14']+x['f15-19']+
                                               x['f20-24']+x['f25-29']+x['f30-34']+x['f35-39']+
                                               x['f40-44']+x['f45-49']+x['f50-54']+x['f55-59']+
                                               x['f60-64']+x['f65-69']+x['f70-74']+x['f75-79']+
                                               x['f80-84']+x['f85+'], axis=1)

In [ ]:
assert((raw_data['m_total']+raw_data['f_total'] == raw_data['Total']).all())

In [ ]:
raw_data = raw_data[['Unnamed: 0', 'index', 'Year', 'SA3 Code', 'SA3 Name', 'm0-4',
       'm5-9', 'm10-14', 'm15-19', 'm20-24', 'm25-29', 'm30-34', 'm35-39',
       'm40-44', 'm45-49', 'm50-54', 'm55-59', 'm60-64', 'm65-69', 'm70-74',
       'm75-79', 'm80-84', 'm85+', 'f0-4', 'f5-9', 'f10-14', 'f15-19',
       'f20-24', 'f25-29', 'f30-34', 'f35-39', 'f40-44', 'f45-49', 'f50-54',
       'f55-59', 'f60-64', 'f65-69', 'f70-74', 'f75-79', 'f80-84', 'f85+',
       'm_total', 'f_total', 'Total']]

In [ ]:
sa3_codes = raw_data['SA3 Code'].unique()

# 2. Split Train, Validation, Test set

In [ ]:
train_data = raw_data[(raw_data['Year']>=1991) & (raw_data['Year']<=2002)]
#val_data = raw_data[(raw_data['Year']>=2002) & (raw_data['Year']<=2005)]
# remove vali 10-10
test_data = raw_data[(raw_data['Year']>=2003) & (raw_data['Year']<=2011)]

In [ ]:
# for 2D
population_per_year_dict = defaultdict(dict)
for sa3_code in sa3_codes:
    population_per_year_dict[sa3_code] = dict()
    for year in range(1991,2012):
        if(raw_data[(raw_data['Year']==year) & (raw_data['SA3 Code']==sa3_code)]['Total'].size>0):
            population_per_year_dict[sa3_code][year] = raw_data[(raw_data['Year']==year) & (raw_data['SA3 Code']==sa3_code)][['m0-4',
                                        'm5-9', 'm10-14', 'm15-19', 'm20-24', 'm25-29', 'm30-34', 'm35-39',
                                        'm40-44', 'm45-49', 'm50-54', 'm55-59', 'm60-64', 'm65-69', 'm70-74',
                                        'm75-79', 'm80-84', 'm85+', 'f0-4', 'f5-9', 'f10-14', 'f15-19',
                                        'f20-24', 'f25-29', 'f30-34', 'f35-39', 'f40-44', 'f45-49', 'f50-54',
                                        'f55-59', 'f60-64', 'f65-69', 'f70-74', 'f75-79', 'f80-84', 'f85+']].values.tolist()[0]

In [ ]:
# for 1D
"""
# Create population dict for each region each year
population_per_year_dict = defaultdict(dict)
for sa3_code in sa3_codes:
    population_per_year_dict[sa3_code] = dict()
    for year in range(1991,2012):
        if(raw_data[(raw_data['Year']==year) & (raw_data['SA3 Code']==sa3_code)]['Total'].size>0):
            population_per_year_dict[sa3_code][year] = raw_data[(raw_data['Year']==year) & (raw_data['SA3 Code']==sa3_code)]['Total'].values[0]
"""

"\n# Create population dict for each region each year\npopulation_per_year_dict = defaultdict(dict)\nfor sa3_code in sa3_codes:\n    population_per_year_dict[sa3_code] = dict()\n    for year in range(1991,2012):\n        if(raw_data[(raw_data['Year']==year) & (raw_data['SA3 Code']==sa3_code)]['Total'].size>0):\n            population_per_year_dict[sa3_code][year] = raw_data[(raw_data['Year']==year) & (raw_data['SA3 Code']==sa3_code)]['Total'].values[0]\n"

In [ ]:
pd.DataFrame(population_per_year_dict)

10101.0  \
1991  [2603, 2565, 2517, 2472, 2178, 2392, 2478, 231...   
1992  [2605, 2567, 2499, 2371, 2183, 2294, 2483, 233...   
1993  [2585, 2557, 2480, 2294, 2145, 2183, 2455, 234...   
1994  [2557, 2551, 2466, 2244, 2098, 2087, 2425, 234...   
1995  [2508, 2561, 2446, 2204, 2018, 2047, 2359, 237...   
1996  [2466, 2582, 2426, 2212, 1914, 2038, 2286, 241...   
1997  [2407, 2557, 2405, 2206, 1809, 2018, 2213, 245...   
1998  [2323, 2584, 2389, 2193, 1775, 1986, 2121, 247...   
1999  [2284, 2592, 2421, 2147, 1787, 1900, 2106, 243...   
2000  [2237, 2580, 2448, 2129, 1785, 1841, 2071, 242...   
2001  [2248, 2450, 2467, 2141, 1740, 1768, 2045, 239...   
2002  [2234, 2419, 2479, 2186, 1749, 1720, 2054, 234...   
2003  [2236, 2399, 2477, 2189, 1793, 1716, 2055, 227...   
2004  [2177, 2398, 2486, 2207, 1766, 1712, 2021, 220...   
2005  [2154, 2366, 2520, 2239, 1771, 1693, 2007, 217...   
2006  [2083, 2368, 2524, 2246, 1777, 1702, 1959, 216...   
2007  [2153, 2321, 2516, 2283, 1780, 1720, 1888, 216...   
2008  [2214, 2326, 2473, 2288, 1801, 1739, 1883, 222...   
2009  [2286, 2305, 2490, 2320, 1863, 1732, 1867, 226...   
2010  [2358, 2297, 2507, 2352, 1870, 1713, 1846, 223...   
2011  [2350, 2338, 2532, 2420, 1806, 1697, 1768, 220...   

                                                10102.0  \
1991  [1593, 1362, 1223, 1406, 1743, 1803, 1670, 139...   
1992  [1625, 1411, 1264, 1375, 1774, 1774, 1741, 147...   
1993  [1638, 1445, 1305, 1348, 1769, 1730, 1785, 155...   
1994  [1643, 1482, 1340, 1334, 1746, 1707, 1834, 161...   
1995  [1631, 1524, 1375, 1328, 1701, 1704, 1841, 168...   
1996  [1610, 1563, 1397, 1336, 1613, 1729, 1828, 175...   
1997  [1700, 1556, 1423, 1342, 1536, 1743, 1791, 183...   
1998  [1750, 1530, 1488, 1327, 1466, 1700, 1803, 185...   
1999  [1777, 1588, 1553, 1368, 1428, 1692, 1810, 191...   
2000  [1820, 1664, 1620, 1454, 1451, 1685, 1861, 204...   
2001  [1709, 1746, 1767, 1565, 1364, 1449, 1759, 206...   
2002  [1742, 1822, 1774, 1598, 1414, 1485, 1823, 203...   
2003  [1778, 1843, 1816, 1675, 1481, 1506, 1887, 205...   
2004  [1761, 1848, 1842, 1740, 1507, 1493, 1879, 201...   
2005  [1790, 1860, 1860, 1804, 1541, 1542, 1857, 205...   
2006  [1826, 1846, 1929, 1833, 1585, 1583, 1801, 215...   
2007  [1841, 1877, 1946, 1860, 1674, 1624, 1807, 219...   
2008  [1869, 1932, 1902, 1877, 1775, 1735, 1802, 222...   
2009  [1897, 1904, 1935, 1874, 1909, 1798, 1799, 220...   
2010  [1917, 1920, 1944, 1877, 1925, 1901, 1792, 218...   
2011  [1937, 1852, 1976, 1898, 1873, 1977, 1789, 210...   

                                                10103.0  \
1991  [741, 641, 577, 591, 848, 1037, 1047, 890, 743...   
1992  [740, 645, 597, 566, 844, 988, 1032, 914, 762,...   
1993  [736, 643, 610, 553, 833, 938, 999, 936, 777, ...   
1994  [728, 650, 626, 539, 812, 900, 980, 953, 804, ...   
1995  [714, 652, 639, 532, 777, 884, 937, 981, 829, ...   
1996  [701, 665, 655, 533, 730, 871, 888, 1005, 861,...   
1997  [706, 664, 633, 566, 678, 837, 814, 999, 865, ...   
1998  [704, 662, 610, 619, 621, 815, 779, 993, 892, ...   
1999  [681, 672, 618, 650, 598, 793, 765, 955, 870, ...   
2000  [643, 657, 634, 677, 609, 784, 733, 881, 887, ...   
2001  [600, 699, 704, 681, 551, 607, 652, 728, 822, ...   
2002  [579, 703, 721, 692, 562, 589, 683, 683, 826, ...   
2003  [571, 709, 720, 672, 562, 594, 656, 677, 833, ...   
2004  [551, 705, 712, 672, 587, 585, 650, 671, 808, ...   
2005  [562, 682, 729, 650, 590, 559, 673, 651, 789, ...   
2006  [584, 656, 735, 646, 582, 546, 645, 691, 758, ...   
2007  [613, 625, 740, 678, 568, 534, 630, 706, 706, ...   
2008  [627, 599, 754, 680, 584, 553, 598, 669, 700, ...   
2009  [649, 584, 762, 679, 593, 559, 558, 672, 714, ...   
2010  [668, 591, 730, 695, 592, 558, 532, 691, 686, ...   
2011  [663, 636, 698, 715, 589, 535, 505, 660, 705, ...   

                                                10104.0  \
1991  [1985, 1987, 1697, 1358, 963, 1258, 1838, 2141...   
1992  [1962, 2038, 1792, 1355, 99

In [ ]:
def split_sequence(sequence, n_steps):
	X, y = list(), list()
	for i in range(len(sequence)):
		# find the end of this pattern
		end_ix = i + n_steps
		# check if we are beyond the sequence
		if end_ix > len(sequence)-1:
			break
		# gather input and output parts of the pattern
		seq_x, seq_y = sequence[i:end_ix], sequence[end_ix]
		X.append(seq_x)
		y.append(seq_y)
	return np.array(X), np.array(y)

In [ ]:
# define input sequence
sample_data = list(population_per_year_dict[10101.0].values())
# choose a number of time steps
n_steps = 5
# split into samples
X, y = split_sequence(sample_data, n_steps)
# summarize the data
for i in range(len(X)):
	print(X[i], y[i])

[[2603 2565 2517 2472 2178 2392 2478 2312 2296 1999 1735 1502 1513 1170
   765  506  260  159 2400 2495 2347 2277 1820 2152 2315 2185 2146 1859
  1591 1412 1382 1252  967  799  493  353]
 [2605 2567 2499 2371 2183 2294 2483 2331 2267 2099 1754 1524 1489 1214
   807  519  269  163 2392 2480 2344 2194 1830 2067 2339 2204 2139 1954
  1607 1433 1378 1260  995  803  511  383]
 [2585 2557 2480 2294 2145 2183 2455 2345 2247 2198 1767 1559 1470 1251
   853  532  280  166 2382 2451 2354 2126 1813 1977 2329 2225 2139 2037
  1625 1466 1371 1266 1030  800  531  417]
 [2557 2551 2466 2244 2098 2087 2425 2348 2244 2241 1827 1584 1447 1284
   898  538  300  169 2357 2418 2351 2084 1777 1913 2316 2232 2158 2079
  1681 1492 1368 1262 1068  781  557  449]
 [2508 2561 2446 2204 2018 2047 2359 2379 2244 2277 1879 1622 1429 1310
   927  561  302  172 2318 2403 2357 2055 1734 1869 2272 2256 2165 2111
  1738 1514 1381 1257 1085  785  571  486]] [2466 2582 2426 2212 1914 2038 2286 2411 2257 2312 1939 1661 142

In [ ]:
# train data
train_x = X[:6]
train_y = y[:6]
# validation data
#val_x = X[6:10]
#val_y = y[6:10]
# test data
test_x = X[6:]
test_y = y[6:]

In [ ]:
# univariate lstm example
from numpy import array
from keras.models import Sequential
from keras.layers import LSTM
from keras.layers import Dense

In [ ]:
# reshape from [samples, timesteps] into [samples, timesteps, features]
n_features = 36
train_x = train_x.reshape((train_x.shape[0], train_x.shape[1], n_features))
# define model
model = Sequential()
model.add(LSTM(50, activation='relu', input_shape=(n_steps, n_features)))
model.add(Dense(36))
model.compile(optimizer='adam', loss='mse')
# fit model
model.fit(train_x, train_y, epochs=200, verbose=0)

# demonstrate prediction
x_input = test_x
predict_list = []
for i in range(len(x_input)):
    temp_x = x_input[i].reshape((1, n_steps, n_features))
    yhat = model.predict(temp_x, verbose=0)
    predict_list.append(yhat)


In [ ]:
predict_list

[array([[2536.057  , 1160.705  , 2755.6658 , 1631.9093 , 1872.8396 ,
         2039.2522 , 2424.765  , 2537.2712 , 2739.9736 , 2486.0374 ,
          971.9601 , 2011.7122 , 1617.3525 , 1433.4628 , 1108.9657 ,
          686.439  ,  378.30988,  223.03227, 1253.3333 , 2350.0808 ,
         2291.631  , 2150.317  , 1559.0779 , 1893.285  , 2279.3213 ,
         2612.6345 , 2449.313  , 2526.1394 ,  892.2703 ,  914.88043,
         1525.0984 , 1399.2589 , 1207.3245 ,  934.2406 ,  644.4479 ,
          612.8215 ]], dtype=float32),
 array([[2550.6328 , 1167.2306 , 2771.9465 , 1640.099  , 1886.1943 ,
         2046.1257 , 2443.329  , 2552.508  , 2761.7805 , 2499.0833 ,
          979.0131 , 2029.0236 , 1622.0979 , 1443.5718 , 1111.3112 ,
          689.81165,  382.84985,  226.63235, 1261.9419 , 2369.8843 ,
         2301.3306 , 2159.1562 , 1564.4487 , 1907.4904 , 2294.2412 ,
         2628.3652 , 2463.4927 , 2546.447  ,  899.6881 ,  920.3373 ,
         1530.4524 , 1409.6937 , 1212.2236 ,  940.11127,  645.49

In [ ]:
np.arry(predict_list[0]

array([[2536.057  , 1160.705  , 2755.6658 , 1631.9093 , 1872.8396 ,
        2039.2522 , 2424.765  , 2537.2712 , 2739.9736 , 2486.0374 ,
         971.9601 , 2011.7122 , 1617.3525 , 1433.4628 , 1108.9657 ,
         686.439  ,  378.30988,  223.03227, 1253.3333 , 2350.0808 ,
        2291.631  , 2150.317  , 1559.0779 , 1893.285  , 2279.3213 ,
        2612.6345 , 2449.313  , 2526.1394 ,  892.2703 ,  914.88043,
        1525.0984 , 1399.2589 , 1207.3245 ,  934.2406 ,  644.4479 ,
         612.8215 ]], dtype=float32)

In [ ]:
test_y[0]

array([2234, 2419, 2479, 2186, 1749, 1720, 2054, 2347, 2455, 2304, 2268,
       2099, 1737, 1386, 1249,  827,  456,  280, 2068, 2319, 2272, 2072,
       1450, 1682, 2080, 2189, 2323, 2239, 2165, 2001, 1632, 1344, 1244,
       1051,  710,  694])

In [ ]:
result1 = (abs(np.array(predict_list) - test_y)/(test_y))
result1

array([[[0.13520899, 0.52017158, 0.11160378, ..., 0.11109362,
         0.09232694, 0.11697194],
        [0.1341936 , 0.51617134, 0.11250132, ..., 0.12030075,
         0.10741291, 0.11185294],
        [0.16493196, 0.51596958, 0.10847376, ..., 0.1293191 ,
         0.14529459, 0.11950938],
        ...,
        [0.10938621, 0.49644037, 0.10669308, ..., 0.13255283,
         0.2775248 , 0.27304689],
        [0.07551183, 0.49468657, 0.09918858, ..., 0.14836773,
         0.31001298, 0.31908725],
        [0.07917314, 0.50354792, 0.08833561, ..., 0.17688053,
         0.34240013, 0.34944642]],

       [[0.14173358, 0.51747392, 0.11817125, ..., 0.10550783,
         0.09084774, 0.1142083 ],
        [0.14071235, 0.51345119, 0.11907409, ..., 0.11477282,
         0.1059583 , 0.10907327],
        [0.17162738, 0.51324829, 0.11502274, ..., 0.12384784,
         0.14390171, 0.11675368],
        ...,
        [0.11576239, 0.49360929, 0.11323154, ..., 0.12710189,
         0.27634741, 0.27077172],
        [0.0

In [ ]:
acc = (predict_list - test_y.tolist())/(test_y.tolist())
acc

TypeError: ignored